version: "3"
services:
  nacos:
    hostname: nacos
    image: nacos/nacos-server:latest
    container_name: nacos-standalone
    environment:
    - PREFER_HOST_MODE=hostname
    - MODE=standalone
    ports:
    - "8848:8848"

  frontend:
    build: ./src/frontend
    image: frontend:1.0.0-SNAPSHOT
    container_name: frontend
#    restart: always
    environment:
      - dubbo.registry.address=nacos://nacos:8848
      - spring.cloud.nacos.discovery.server-addr=nacos:8848
      - spring.cloud.nacos.config.server-addr=nacos:8848
    ports:
      - "8080:8080"
    depends_on:
      - "nacos"

  cartservice:
    image: cartservice:1.0.0-SNAPSHOT
    container_name: cartservice
    environment:
      - dubbo.registry.address=nacos://nacos:8848
      - spring.cloud.nacos.discovery.server-addr=nacos:8848
      - spring.cloud.nacos.config.server-addr=nacos:8848
    depends_on:
      - "nacos"

  checkoutservice:
    build: ./src/checkoutservice
    image: checkoutservice:1.0.0-SNAPSHOT
    container_name: checkoutservice
    environment:
    - dubbo.registry.address=nacos://nacos:8848
    - spring.cloud.nacos.discovery.server-addr=nacos:8848
    - spring.cloud.nacos.config.server-addr=nacos:8848
    depends_on:
      - "nacos"

  prdoctservice:
    build: ./src/productservice
    image: productservice:1.0.0-SNAPSHOT
    container_name: productservice
    environment:
    - dubbo.registry.address=nacos://nacos:8848
    - spring.cloud.nacos.discovery.server-addr=nacos:8848
    - spring.cloud.nacos.config.server-addr=nacos:8848
    depends_on:
      - "nacos"

#  adservice:
#    build: ./src/adservice
#    image: adservice:1.0.0-SNAPSHOT
#    container_name: adservice
#    environment:
#      - dubbo.registry.address=nacos://nacos:8848
#      - spring.cloud.nacos.discovery.server-addr=nacos:8848
#      - spring.cloud.nacos.discovery.server-addr=nacos:8848
#    depends_on:
#      - "nacos"
#
#
#
#  currencyservice:
#    build: ./src/productservice
#    image: currencyservice:1.0.0-SNAPSHOT
#    container_name: currencyservice
#    environment:
#      - dubbo.registry.address=nacos://nacos:8848
#      - spring.cloud.nacos.discovery.server-addr=nacos:8848
#      - spring.cloud.nacos.discovery.server-addr=nacos:8848
#    depends_on:
#      - "nacos"
#
#  emailservice:
#    build: ./src/emailservice
#    image: emailservice:1.0.0-SNAPSHOT
#    container_name: emailservice
#    environment:
#      - dubbo.registry.address=nacos://nacos:8848
#      - spring.cloud.nacos.discovery.server-addr=nacos:8848
#      - spring.cloud.nacos.discovery.server-addr=nacos:8848
#    depends_on:
#      - "nacos"
#
#  paymentservice:
#    build: ./src/paymentservice
#    image: paymentservice:1.0.0-SNAPSHOT
#    container_name: paymentservice
#    environment:
#      - dubbo.registry.address=nacos://nacos:8848
#      - spring.cloud.nacos.discovery.server-addr=nacos:8848
#      - spring.cloud.nacos.discovery.server-addr=nacos:8848
#    depends_on:
#      - "nacos"
#
#  recomendationservice:
#    build: ./src/recomendationservice
#    image: recomendationservice:1.0.0-SNAPSHOT
#    container_name: recomendationservice
#    environment:
#      - dubbo.registry.address=nacos://nacos:8848
#      - spring.cloud.nacos.discovery.server-addr=nacos:8848
#      - spring.cloud.nacos.discovery.server-addr=nacos:8848
#    depends_on:
#      - "nacos"
#
#  shippingservice:
#    build: ./src/shippingservice
#    image: shippingservice:1.0.0-SNAPSHOT
#    container_name: shippingservice
#    environment:
#      - dubbo.registry.address=nacos://nacos:8848
#      - spring.cloud.nacos.discovery.server-addr=nacos:8848
#      - spring.cloud.nacos.discovery.server-addr=nacos:8848
#    depends_on:
#      - "nacos"