apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice
spec:
  selector:
    matchLabels:
      app: productservice
  template:
    metadata:
      labels:
        app: productservice
        version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - name: productservice
          image: productservice:1.0.0-SNAPSHOT
          env:
            - name: dubbo.registry.address
              value: "nacos://nacos:8848"
            - name: spring.cloud.nacos.discovery.server-addr
              value: "nacos:8848"
            - name: spring.cloud.nacos.config.server-addr
              value: "nacos:8848"