apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.productservice.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.productservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.productservice.name }}
    spec:
      containers:
        - name: {{ .Values.productservice.name }}
          image: {{ .Values.productservice.image }}
          env:
            - name: dubbo.registry.address
              value: "nacos://{{ .Values.nacos.host }}:{{ .Values.nacos.port }}"
            - name: spring.cloud.nacos.discovery.server-addr
              value: "{{ .Values.nacos.host }}:{{ .Values.nacos.port }}"
            - name: spring.cloud.nacos.config.server-addr
              value: "{{ .Values.nacos.host }}:{{ .Values.nacos.port }}"